services:
  engine:
    build: .
    volumes:
      - .:/app
    command: python tests/sanity_check.py
    deploy:
      resources:
        limits:
          cpus: '1.0'        
          memory: 300M      
    environment:
      - PYTHONOPTIMIZE=1    
      - PYTHONDONTWRITEBYTECODE=1