services:
  engine:
    build: .
    volumes:
      - .:/app
    command: python -m tests.sanity_check
    deploy:
      resources:
        limits:
          cpus: '1.0'        
          memory: 300M      
    environment:
      - PYTHONOPTIMIZE=/app
      - PYTHONOPTIMIZE=1